# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 016d9679d3df0863359f7e78d3e57d603b2c231903a5069fdae50dc80f1c496bef77ecfda45a7c80811cf2e54d31b70d2a8591fc20a1924ea74be2ca22817afe

test:
  secret_key_base: 11e21c718b15ba02695f5af3d8648ae536e0647782bc923e9515647ee330c2968595411d3a4b48a405dd07fc8804da0a8d85d601503973b581323cb2224525ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
